import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Input } from "@/components/ui/Input";
import { Modal } from "@/components/ui/Modal";
import { Spinner } from "@/components/ui/Spinner";
import * as portal from "@/services/parentPortal.service";
import { ParentDashboardChild, ReportCard } from "@/types/parent.types";
import { DAY_NAMES } from "@/types/dashboard.types";

export function ParentDashboardPage() {
  const cache = useQueryClient();
  const [studentId, setStudentId] = useState("");
  const [leaveOpen, setLeaveOpen] = useState(false);
  const dashboard = useQuery({ queryKey: ["parent-dashboard"], queryFn: portal.fetchDashboard });
  const leaves = useQuery({ queryKey: ["parent-leaves"], queryFn: portal.fetchLeaveRequests });
  const selected = useMemo(() => {
    const children = dashboard.data?.children ?? [];
    return children.find((entry) => entry.child.id === studentId) ?? children[0];
  }, [dashboard.data, studentId]);
  const submitLeave = useMutation({ mutationFn: portal.applyForLeave, onSuccess: () => { void cache.invalidateQueries({ queryKey: ["parent-leaves"] }); setLeaveOpen(false); } });

  if (dashboard.isLoading) return <Spinner label="Loading your children’s information..." />;
  if (dashboard.isError) return <p className="text-sm text-red-600">Unable to load the parent dashboard.</p>;
  if (!selected) return <Card><p className="text-sm text-slate-600">No students are linked to this parent account. Please contact the school office.</p></Card>;
  return <div className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold text-slate-900">Parent dashboard</h1><p className="text-sm text-slate-500">Track learning, attendance, and school updates.</p></div><Button onClick={() => setLeaveOpen(true)}>Apply for leave</Button></div>
    {(dashboard.data?.children.length ?? 0) > 1 && <label className="block max-w-sm text-sm font-medium text-slate-700">Student<select className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" value={selected.child.id} onChange={(event) => setStudentId(event.target.value)}>{dashboard.data!.children.map(({ child }) => <option key={child.id} value={child.id}>{child.users?.full_name ?? "Student"} — {child.admission_no}</option>)}</select></label>}
    <ChildHeader item={selected} />
    <div className="grid grid-cols-1 gap-6 lg:grid-cols-2"><Attendance item={selected} /><Marks item={selected} /></div>
    <div className="grid grid-cols-1 gap-6 lg:grid-cols-2"><Homework item={selected} /><Updates item={selected} /></div>
    <Timetable item={selected} />
    <Card><h2 className="text-lg font-semibold">Leave requests</h2>{leaves.isLoading ? <p className="mt-3 text-sm text-slate-500">Loading…</p> : leaves.data?.length ? <ul className="mt-3 space-y-2">{leaves.data.map((leave) => <li key={leave.id} className="flex flex-wrap justify-between gap-2 rounded border p-3 text-sm"><span>{leave.students?.users?.full_name ?? "Student"}: {leave.start_date} to {leave.end_date}</span><b className="capitalize">{leave.status}</b></li>)}</ul> : <p className="mt-3 text-sm text-slate-500">No leave requests submitted.</p>}</Card>
    <LeaveModal item={selected} isOpen={leaveOpen} loading={submitLeave.isPending} error={submitLeave.isError} onClose={() => setLeaveOpen(false)} onSubmit={(input) => submitLeave.mutate(input)} />
  </div>;
}

function ChildHeader({ item }: { item: ParentDashboardChild }) { return <Card className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">{item.child.users?.full_name ?? "Student"}</h2><p className="text-sm text-slate-500">{item.child.classes ? `${item.child.classes.name} ${item.child.classes.section}` : "Class not assigned"} · Admission no. {item.child.admission_no}</p></div><Button variant="secondary" onClick={() => void portal.fetchReportCard(item.child.id).then(downloadReport)}>Download report card</Button></Card>; }
function Attendance({ item }: { item: ParentDashboardChild }) { const data = item.overview.attendance; return <Card><h2 className="text-lg font-semibold">Attendance</h2><p className="mt-3 text-3xl font-bold">{data.percentage === null ? "—" : `${data.percentage}%`}</p><p className="text-sm text-slate-500">{data.total} recorded day(s), {data.from} to {data.to}</p><div className="mt-3 grid grid-cols-3 gap-2 text-sm">{Object.entries(data.counts).map(([status, count]) => <div key={status} className="rounded border p-2"><b>{count}</b><br /><span className="capitalize text-slate-500">{status.replace("_", " ")}</span></div>)}</div></Card>; }
function Marks({ item }: { item: ParentDashboardChild }) { const latest = item.overview.marks.latestExam; return <Card><h2 className="text-lg font-semibold">Marks</h2>{latest ? <><div className="mt-3 flex justify-between"><span>{latest.examName}</span><b>{latest.percentage ?? "—"}%</b></div><ul className="mt-3 space-y-2 text-sm">{latest.subjects.map((mark) => <li className="flex justify-between border-b pb-1" key={mark.subjectId}><span>{mark.subjectName}</span><span>{mark.marksObtained}/{mark.maxMarks} {mark.grade ? `(${mark.grade})` : ""}</span></li>)}</ul></> : <p className="mt-3 text-sm text-slate-500">No published results yet.</p>}</Card>; }
function Homework({ item }: { item: ParentDashboardChild }) { return <Card><h2 className="text-lg font-semibold">Homework</h2>{item.overview.homework.length ? <ul className="mt-3 space-y-3">{item.overview.homework.map((work) => <li key={work.id} className="rounded border p-3 text-sm"><div className="flex justify-between gap-2"><b>{work.title}</b><span>Due {work.due_date}</span></div><p className="text-slate-500">{work.subjects?.name}</p><p>{work.description}</p>{work.attachment_url && <a className="text-brand-700" href={work.attachment_url} target="_blank" rel="noreferrer">Open attachment</a>}</li>)}</ul> : <p className="mt-3 text-sm text-slate-500">No upcoming homework.</p>}</Card>; }
function Updates({ item }: { item: ParentDashboardChild }) { return <Card><h2 className="text-lg font-semibold">School updates</h2>{item.overview.notifications.length ? <ul className="mt-3 space-y-3">{item.overview.notifications.map((notice) => <li key={notice.id} className="rounded border p-3 text-sm"><b>{notice.title}</b><p>{notice.message}</p><p className="mt-1 text-xs text-slate-400">{new Date(notice.created_at).toLocaleString()}</p></li>)}</ul> : <p className="mt-3 text-sm text-slate-500">No school updates.</p>}</Card>; }
function Timetable({ item }: { item: ParentDashboardChild }) { return <Card><h2 className="text-lg font-semibold">Timetable</h2>{item.overview.timetable.length ? <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{item.overview.timetable.map((day) => <div key={day.dayOfWeek}><b className="text-sm">{DAY_NAMES[day.dayOfWeek]}</b>{day.periods.map((period) => <p key={period.id} className="mt-1 rounded border px-2 py-1 text-sm">{period.start_time.slice(0, 5)}–{period.end_time.slice(0, 5)} · {period.subjects?.name ?? "—"}</p>)}</div>)}</div> : <p className="mt-3 text-sm text-slate-500">No timetable published.</p>}</Card>; }
function LeaveModal({ item, isOpen, loading, error, onClose, onSubmit }: { item: ParentDashboardChild; isOpen: boolean; loading: boolean; error: boolean; onClose: () => void; onSubmit: (value: { student_id: string; start_date: string; end_date: string; reason: string }) => void }) { const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [reason, setReason] = useState(""); return <Modal isOpen={isOpen} onClose={onClose} title="Apply for leave"><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); onSubmit({ student_id: item.child.id, start_date: start, end_date: end, reason }); }}><Input label="Start date" type="date" value={start} onChange={(event) => setStart(event.target.value)} required /><Input label="End date" type="date" min={start} value={end} onChange={(event) => setEnd(event.target.value)} required /><label className="flex flex-col gap-1.5 text-sm font-medium text-slate-700">Reason<textarea className="rounded-md border border-slate-300 px-3 py-2" value={reason} onChange={(event) => setReason(event.target.value)} minLength={5} maxLength={1000} required /></label>{error && <p className="text-sm text-red-600">Could not submit the request.</p>}<Button type="submit" isLoading={loading}>Submit request</Button></form></Modal>; }
function downloadReport(report: ReportCard) { const rows = report.marks.exams.flatMap((exam) => exam.subjects.map((mark) => `<tr><td>${safe(exam.examName)}</td><td>${safe(mark.subjectName)}</td><td>${mark.marksObtained}/${mark.maxMarks}</td><td>${safe(mark.grade ?? "")}</td></tr>`)).join(""); const html = `<html><body><h1>Report card</h1><p>${safe(report.student.users?.full_name ?? "Student")} · ${safe(report.student.admission_no)} · Attendance: ${report.attendance.percentage ?? "—"}%</p><table border="1"><tr><th>Exam</th><th>Subject</th><th>Marks</th><th>Grade</th></tr>${rows || "<tr><td colspan=4>No marks published.</td></tr>"}</table></body></html>`; const url = URL.createObjectURL(new Blob([html], { type: "text/html" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${report.student.admission_no}-report-card.html`; anchor.click(); URL.revokeObjectURL(url); }
function safe(value: string) { return value.replace(/[&<>\"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '\"': "&quot;" })[char] ?? char); }
