import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Spinner } from "@/components/ui/Spinner";
import { LiveMap } from "@/components/tracking/LiveMap";
import * as transport from "@/services/transport.service";
import * as tracking from "@/services/tracking.service";
import { LiveTrip } from "@/types/tracking.types";
export function DriverDashboardPage() {
  const cache = useQueryClient(); const dashboard = useQuery({ queryKey: ["driver-transport"], queryFn: transport.fetchDriverDashboard }); const [activeTrip, setActiveTrip] = useState<LiveTrip | null>(null); const [position, setPosition] = useState<{ latitude: number; longitude: number; updatedAt: string } | null>(null); const [gpsError, setGpsError] = useState(""); const lastSent = useRef(0);
  const start = useMutation({ mutationFn: () => tracking.startTrip(), onSuccess: (trip) => { setActiveTrip(trip); setGpsError(""); void cache.invalidateQueries({ queryKey: ["driver-transport"] }); } }); const end = useMutation({ mutationFn: () => tracking.endTrip(activeTrip!.id), onSuccess: () => { setActiveTrip(null); void cache.invalidateQueries({ queryKey: ["driver-transport"] }); } });
  useEffect(() => { if (!activeTrip) return; if (!navigator.geolocation) { setGpsError("This browser does not support location sharing."); return; } const watcher = navigator.geolocation.watchPosition((point) => { const now = Date.now(); const next = { latitude: point.coords.latitude, longitude: point.coords.longitude, updatedAt: new Date(point.timestamp).toISOString() }; setPosition(next); if (now - lastSent.current >= 10000 || point.coords.accuracy <= 25) { lastSent.current = now; void tracking.sendLocation(activeTrip.id, { latitude: next.latitude, longitude: next.longitude, accuracy_meters: point.coords.accuracy, speed_mps: point.coords.speed ?? undefined, heading: point.coords.heading ?? undefined, recorded_at: next.updatedAt }).catch(() => setGpsError("Location could not be sent. Check your connection.")); } }, (error) => setGpsError(error.code === error.PERMISSION_DENIED ? "Location permission is required while a trip is active." : "Unable to determine your location."), { enableHighAccuracy: true, maximumAge: 5000, timeout: 20000 }); return () => navigator.geolocation.clearWatch(watcher); }, [activeTrip]);
  if (dashboard.isLoading) return <Spinner label="Loading transport assignment..." />; if (!dashboard.data?.vehicle) return <Card><h1 className="text-xl font-semibold">Driver dashboard</h1><p className="mt-2 text-sm text-slate-500">No active vehicle is assigned to you.</p></Card>; const { vehicle, pickup_points, students } = dashboard.data;
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">Driver dashboard</h1><p className="text-sm text-slate-500">Use a secure HTTPS mobile browser and keep this page open during the trip.</p></div>{activeTrip ? <Button variant="danger" onClick={() => end.mutate()} isLoading={end.isPending}>End trip</Button> : <Button onClick={() => start.mutate()} isLoading={start.isPending}>Start trip & share GPS</Button>}</div><div className="grid gap-6 md:grid-cols-2"><Card><h2 className="text-lg font-semibold">Assigned vehicle</h2><p className="mt-2 text-xl font-bold">{vehicle.vehicle_number}</p><p className="text-sm text-slate-500">{vehicle.make_model ?? "Vehicle"} · Capacity {vehicle.capacity}</p></Card><Card><h2 className="text-lg font-semibold">Route</h2><p className="mt-2 font-medium">{vehicle.routes?.name ?? "No route assigned"}</p><p className="text-sm text-slate-500">{vehicle.routes?.route_code}</p></Card></div>{activeTrip && <Card><h2 className="text-lg font-semibold">Live location</h2><p className="mt-1 text-sm text-slate-500">GPS is shared every 10 seconds while the trip is active.</p>{gpsError && <p className="mt-2 text-sm text-red-600">{gpsError}</p>}<div className="mt-3">{position ? <LiveMap locations={[{ vehicleId: vehicle.id, latitude: position.latitude, longitude: position.longitude, label: vehicle.vehicle_number, updatedAt: position.updatedAt }]} height="300px" /> : <p className="text-sm text-slate-500">Waiting for GPS permission and first location…</p>}</div></Card>}<Card><h2 className="text-lg font-semibold">Student pickup list</h2>{students.length ? <ul className="mt-3 space-y-2">{students.map((entry) => <li key={entry.students.id} className="flex justify-between rounded border p-3 text-sm"><span>{entry.students.users.full_name}</span><span className="text-slate-500">{pickup_points.find((point) => point.id === entry.pickup_point_id)?.name ?? "Pickup point"}</span></li>)}</ul> : <p className="mt-2 text-sm text-slate-500">No students assigned.</p>}</Card></div>;
}
