import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Card } from "@/components/ui/Card";
import { Spinner } from "@/components/ui/Spinner";
import { LiveMap } from "@/components/tracking/LiveMap";
import { supabase } from "@/lib/supabaseClient";
import * as tracking from "@/services/tracking.service";
import { LiveLocation, LiveTrip } from "@/types/tracking.types";
export function AdminVehicleTrackingPage() { const active = useQuery({ queryKey: ["active-vehicles"], queryFn: tracking.fetchActiveVehicles, refetchInterval: 60000 }); const [locations, setLocations] = useState<Record<string, LiveLocation>>({}); useEffect(() => { const channel = supabase.channel("admin-vehicle-locations").on("postgres_changes", { event: "INSERT", schema: "public", table: "vehicle_locations" }, (event) => { const row = event.new as { vehicle_id: string; latitude: number; longitude: number; recorded_at: string }; setLocations((current) => ({ ...current, [row.vehicle_id]: { vehicleId: row.vehicle_id, latitude: Number(row.latitude), longitude: Number(row.longitude), label: "School van", updatedAt: row.recorded_at } })); }).subscribe(); return () => { void supabase.removeChannel(channel); }; }, []); if (active.isLoading) return <Spinner label="Loading active vehicles..." />; const trips = active.data ?? []; const mapLocations = trips.map((trip) => locations[trip.vehicle_id] ?? tripLocation(trip)).filter((value): value is LiveLocation => !!value); return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Live vehicle tracking</h1><p className="text-sm text-slate-500">All active school vehicles. Updates arrive through Supabase Realtime.</p></div>{mapLocations.length ? <LiveMap locations={mapLocations} /> : <Card><p className="text-sm text-slate-500">No active vehicle locations yet.</p></Card>}<Card><h2 className="text-lg font-semibold">Active trips</h2>{trips.length ? <ul className="mt-3 space-y-2">{trips.map((trip) => <li key={trip.id} className="rounded border p-3 text-sm"><b>{trip.vehicles?.vehicle_number ?? "Vehicle"}</b> · {trip.vehicles?.routes?.name ?? "No route"} · {trip.drivers?.users?.full_name ?? "Driver"}<p className="text-slate-500">Started {new Date(trip.started_at).toLocaleTimeString()} · Last GPS {trip.last_location_at ? new Date(trip.last_location_at).toLocaleTimeString() : "pending"}</p></li>)}</ul> : <p className="mt-3 text-sm text-slate-500">No trips are currently active.</p>}</Card></div>; }
function tripLocation(trip: LiveTrip): LiveLocation | null { return trip.last_latitude !== null && trip.last_longitude !== null ? { vehicleId: trip.vehicle_id, latitude: Number(trip.last_latitude), longitude: Number(trip.last_longitude), label: trip.vehicles?.vehicle_number ?? "Vehicle", updatedAt: trip.last_location_at } : null; }
