import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Card } from "@/components/ui/Card";
import { Spinner } from "@/components/ui/Spinner";
import { LiveMap } from "@/components/tracking/LiveMap";
import { supabase } from "@/lib/supabaseClient";
import * as tracking from "@/services/tracking.service";
import { LiveLocation } from "@/types/tracking.types";
export function ParentVanTrackingPage() { const query = useQuery({ queryKey: ["parent-van-tracking"], queryFn: tracking.fetchParentVehicles }); const [live, setLive] = useState<Record<string, LiveLocation>>({}); useEffect(() => { const channel = supabase.channel("parent-van-locations").on("postgres_changes", { event: "INSERT", schema: "public", table: "vehicle_locations" }, (event) => { const row = event.new as { vehicle_id: string; latitude: number; longitude: number; recorded_at: string }; setLive((current) => ({ ...current, [row.vehicle_id]: { vehicleId: row.vehicle_id, latitude: Number(row.latitude), longitude: Number(row.longitude), label: "School van", updatedAt: row.recorded_at } })); }).subscribe(); return () => { void supabase.removeChannel(channel); }; }, []); if (query.isLoading) return <Spinner label="Loading van location..." />; const assignments = query.data ?? []; const vans = assignments.flatMap((a) => a.pickup_points.routes.vehicles.map((v) => ({ assignment: a, vehicle: v, trip: v.trips.find((t) => t.status === "in_progress") }))); const locations = vans.map(({ vehicle, trip }) => live[vehicle.id] ?? (trip?.last_latitude !== null && trip?.last_longitude !== null ? { vehicleId: vehicle.id, latitude: Number(trip.last_latitude), longitude: Number(trip.last_longitude), label: vehicle.vehicle_number, updatedAt: trip.last_location_at } : null)).filter((value): value is LiveLocation => !!value); return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">School van tracking</h1><p className="text-sm text-slate-500">Live updates appear automatically while your child’s assigned van is on a trip.</p></div>{locations.length ? <LiveMap locations={locations} /> : <Card><p className="text-sm text-slate-500">No assigned van is currently sharing a live location.</p></Card>}<div className="space-y-4">{vans.map(({ assignment, vehicle, trip }) => <Card key={`${assignment.students.id}-${vehicle.id}`}><h2 className="text-lg font-semibold">{assignment.students.users?.full_name ?? "Student"} — {vehicle.vehicle_number}</h2><p className="text-sm text-slate-500">{assignment.pickup_points.routes.route_code} · {assignment.pickup_points.routes.name}</p><p className="mt-2 text-sm">Pickup point: <b>{assignment.pickup_points.name}</b></p><p className="text-sm">Scheduled ETA: <b>{assignment.pickup_points.pickup_time?.slice(0, 5) ?? "Not set"}</b></p><p className="mt-2 text-sm text-slate-500">{trip ? `Trip is active (${trip.direction}). Last update: ${trip.last_location_at ? new Date(trip.last_location_at).toLocaleTimeString() : "waiting for GPS"}` : "No active trip."}</p></Card>)}</div></div>; }
