import { supabaseAdmin } from "../config/supabase";
import { ApiError } from "../utils/ApiError";
const fail = (error: { message: string } | null) => { if (error) throw ApiError.internal(error.message); };
async function assignedVehicle(schoolId: string, driverId: string) { const r = await supabaseAdmin.from("vehicles").select("id, route_id").eq("school_id", schoolId).eq("driver_id", driverId).eq("is_active", true).maybeSingle(); fail(r.error); if (!r.data) throw ApiError.forbidden("No active vehicle is assigned to this driver"); return r.data; }
export async function startTrip(schoolId: string, driverId: string, direction: "pickup" | "drop") { const vehicle = await assignedVehicle(schoolId, driverId); const existing = await supabaseAdmin.from("trips").select("id, vehicle_id, route_id, trip_date, direction, status, started_at").eq("vehicle_id", vehicle.id).eq("status", "in_progress").maybeSingle(); fail(existing.error); if (existing.data) return existing.data; const r = await supabaseAdmin.from("trips").insert({ school_id: schoolId, driver_id: driverId, vehicle_id: vehicle.id, route_id: vehicle.route_id, direction, status: "in_progress", started_at: new Date().toISOString() }).select().single(); fail(r.error); await supabaseAdmin.from("trip_history").insert({ school_id: schoolId, trip_id: r.data.id, event_type: "started" }); return r.data; }
export async function recordLocation(schoolId: string, driverId: string, tripId: string, input: { latitude: number; longitude: number; accuracy_meters?: number; speed_mps?: number; heading?: number; recorded_at?: string }) { const trip = await supabaseAdmin.from("trips").select("id, vehicle_id, driver_id, status").eq("id", tripId).eq("school_id", schoolId).eq("driver_id", driverId).maybeSingle(); fail(trip.error); if (!trip.data || trip.data.status !== "in_progress") throw ApiError.forbidden("Location updates require your active trip"); const now = input.recorded_at ?? new Date().toISOString(); const location = await supabaseAdmin.from("vehicle_locations").insert({ school_id: schoolId, trip_id: tripId, vehicle_id: trip.data.vehicle_id, driver_id: driverId, ...input, recorded_at: now }).select().single(); fail(location.error); const update = await supabaseAdmin.from("trips").update({ last_latitude: input.latitude, last_longitude: input.longitude, last_location_at: now }).eq("id", tripId).eq("driver_id", driverId); fail(update.error); await supabaseAdmin.from("trip_history").insert({ school_id: schoolId, trip_id: tripId, event_type: "location", latitude: input.latitude, longitude: input.longitude, occurred_at: now, metadata: { accuracy_meters: input.accuracy_meters, speed_mps: input.speed_mps, heading: input.heading } }); return location.data; }
export async function endTrip(schoolId: string, driverId: string, tripId: string) { const r = await supabaseAdmin.from("trips").update({ status: "completed", completed_at: new Date().toISOString() }).eq("id", tripId).eq("school_id", schoolId).eq("driver_id", driverId).eq("status", "in_progress").select().maybeSingle(); fail(r.error); if (!r.data) throw ApiError.notFound("Active trip not found"); await supabaseAdmin.from("trip_history").insert({ school_id: schoolId, trip_id: tripId, event_type: "completed" }); return r.data; }
export async function parentVehicles(schoolId: string, parentId: string) { const r = await supabaseAdmin.from("student_pickup_points").select("students!inner(id, users(full_name), student_parents!inner(parent_id)), pickup_points!inner(id, name, pickup_time, routes!inner(id, name, route_code, vehicles(id, vehicle_number, trips(id, status, last_latitude, last_longitude, last_location_at, direction, started_at))))").eq("school_id", schoolId).eq("students.student_parents.parent_id", parentId).eq("is_active", true); fail(r.error); return r.data ?? []; }
export async function activeVehicles(schoolId: string) { const r = await supabaseAdmin.from("trips").select("id, vehicle_id, direction, started_at, last_latitude, last_longitude, last_location_at, vehicles(vehicle_number, routes(name, route_code)), drivers(users(full_name))").eq("school_id", schoolId).eq("status", "in_progress").order("started_at", { ascending: false }); fail(r.error); return r.data; }
