import { supabaseAdmin } from "../config/supabase";
import { env } from "../config/env";
import { ROLE_ID } from "../config/roles";
import { ApiError } from "../utils/ApiError";
const check = (error: { message: string; code?: string } | null) => { if (error) { if (error.code === "23505") throw ApiError.conflict(error.message); throw ApiError.internal(error.message); } };
export async function listVehicles(schoolId: string) { const r = await supabaseAdmin.from("vehicles").select("id, vehicle_number, capacity, driver_id, route_id, make_model, gps_device_id, is_active, drivers(users(full_name)), routes(name, route_code)").eq("school_id", schoolId).order("vehicle_number"); check(r.error); return r.data; }
export async function createVehicle(schoolId: string, input: Record<string, unknown>) { const r = await supabaseAdmin.from("vehicles").insert({ school_id: schoolId, ...input }).select().single(); check(r.error); return r.data; }
export async function listDrivers(schoolId: string) { const r = await supabaseAdmin.from("drivers").select("id, license_number, license_expiry, users(full_name, email, phone, is_active)").eq("school_id", schoolId).order("license_number"); check(r.error); return r.data; }
export async function createDriver(schoolId: string, input: { email: string; full_name: string; phone?: string; license_number: string; license_expiry?: string }) { const invite = await supabaseAdmin.auth.admin.inviteUserByEmail(input.email, { redirectTo: `${env.FRONTEND_URL}/reset-password`, data: { full_name: input.full_name, role_id: ROLE_ID.DRIVER, school_id: schoolId } }); if (invite.error || !invite.data.user) { if (invite.error?.status === 422) throw ApiError.conflict("A user with this email already exists"); throw ApiError.internal(invite.error?.message ?? "Could not invite driver"); } const id = invite.data.user.id; if (input.phone) await supabaseAdmin.from("users").update({ phone: input.phone }).eq("id", id); const result = await supabaseAdmin.from("drivers").insert({ id, school_id: schoolId, license_number: input.license_number, license_expiry: input.license_expiry }); if (result.error) { await supabaseAdmin.auth.admin.deleteUser(id); check(result.error); } return { id }; }
export async function listRoutes(schoolId: string) { const r = await supabaseAdmin.from("routes").select("id, name, route_code, description, is_active, pickup_points(id, name, address, stop_order, pickup_time, latitude, longitude)").eq("school_id", schoolId).order("route_code"); check(r.error); return r.data; }
export async function createRoute(schoolId: string, input: Record<string, unknown>) { const r = await supabaseAdmin.from("routes").insert({ school_id: schoolId, ...input }).select().single(); check(r.error); return r.data; }
export async function createPickupPoint(schoolId: string, input: Record<string, unknown>) { const r = await supabaseAdmin.from("pickup_points").insert({ school_id: schoolId, ...input }).select().single(); check(r.error); return r.data; }
export async function assignStudentPickup(schoolId: string, input: { student_id: string; pickup_point_id: string }) { const point = await supabaseAdmin.from("pickup_points").select("id").eq("id", input.pickup_point_id).eq("school_id", schoolId).maybeSingle(); check(point.error); if (!point.data) throw ApiError.notFound("Pickup point not found"); const r = await supabaseAdmin.from("student_pickup_points").upsert({ school_id: schoolId, ...input }, { onConflict: "student_id" }).select().single(); check(r.error); return r.data; }
export async function getDriverDashboard(schoolId: string, driverId: string) { const vehicle = await supabaseAdmin.from("vehicles").select("id, vehicle_number, capacity, make_model, route_id, routes(id, name, route_code, description)").eq("school_id", schoolId).eq("driver_id", driverId).eq("is_active", true).maybeSingle(); check(vehicle.error); if (!vehicle.data) return { vehicle: null, pickup_points: [], students: [], trips: [] }; const points = vehicle.data.route_id ? await supabaseAdmin.from("pickup_points").select("id, name, address, stop_order, pickup_time").eq("route_id", vehicle.data.route_id).order("stop_order") : { data: [], error: null }; check(points.error); const ids = (points.data ?? []).map((p) => p.id); const students = ids.length ? await supabaseAdmin.from("student_pickup_points").select("pickup_point_id, students(id, admission_no, users(full_name), classes(name, section))").eq("school_id", schoolId).eq("is_active", true).in("pickup_point_id", ids) : { data: [], error: null }; check(students.error); const trips = await supabaseAdmin.from("trips").select("id, trip_date, direction, status, last_latitude, last_longitude, last_location_at").eq("driver_id", driverId).eq("trip_date", new Date().toISOString().slice(0, 10)).order("created_at", { ascending: false }); check(trips.error); return { vehicle: vehicle.data, pickup_points: points.data ?? [], students: students.data ?? [], trips: trips.data ?? [] }; }
