import { Router } from "express";
import authRoutes from "./auth.routes";
import healthRoutes from "./health.routes";
import schoolRoutes from "./school.routes";
import userRoutes from "./user.routes";
import classRoutes from "./class.routes";
import studentRoutes from "./student.routes";
import teacherRoutes from "./teacher.routes";
import teacherPortalRoutes from "./teacherPortal.routes";
import attendanceRoutes from "./attendance.routes";
import examRoutes from "./exam.routes";
import homeworkRoutes from "./homework.routes";
import timetableRoutes from "./timetable.routes";
import notificationRoutes from "./notification.routes";
import transportRoutes from "./transport.routes";
import trackingRoutes from "./tracking.routes";
import reportsRoutes from "./reports.routes";
import feesRoutes from "./fees.routes";
import teacherAttendanceRoutes from "./teacherAttendance.routes";
import leaveRequestRoutes from "./leaveRequest.routes";
import studentLeaveRequestRoutes from "./studentLeaveRequest.routes";
import studentProfileChangeRequestRoutes from "./studentProfileChangeRequest.routes";
import timetableChangeRequestRoutes from "./timetableChangeRequest.routes";
import announcementRoutes from "./announcement.routes";
import pushRoutes from "./push.routes";
import rbacRoutes from "./rbac.routes";
import auditLogRoutes from "./auditLog.routes";
import activityRoutes from "./activity.routes";
import extracurricularStaffRoutes from "./extracurricularStaff.routes";
import extracurricularPortalRoutes from "./extracurricularPortal.routes";
import { queueRouter as registrationRequestRoutes } from "./registration.routes";
import syllabusRoutes from "./syllabus.routes";
import superAdminRoutes from "./superAdmin.routes";
import schoolRequestRoutes from "./schoolRequest.routes";
import websiteKnowledgeRoutes from "./websiteKnowledge.routes";
import learningGamesRoutes from "./learningGames.routes";

const router = Router();

router.use("/health", healthRoutes);
router.use("/auth", authRoutes);
router.use("/schools", schoolRoutes);
router.use("/users", userRoutes);
router.use("/students", studentRoutes);
router.use("/teachers", teacherRoutes);
router.use("/teacher-portal", teacherPortalRoutes);
router.use("/transport", transportRoutes);
router.use("/tracking", trackingRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/exams", examRoutes);
router.use("/homework", homeworkRoutes);
router.use("/timetable", timetableRoutes);
router.use("/notifications", notificationRoutes);
router.use("/reports", reportsRoutes);
router.use("/fees", feesRoutes);
router.use("/teacher-attendance", teacherAttendanceRoutes);
router.use("/leave-requests", leaveRequestRoutes);
router.use("/student-leave-requests", studentLeaveRequestRoutes);
router.use("/profile-change-requests", studentProfileChangeRequestRoutes);
router.use("/timetable-change-requests", timetableChangeRequestRoutes);
router.use("/announcements", announcementRoutes);
router.use("/push", pushRoutes);
router.use("/audit", auditLogRoutes);
router.use("/activities", activityRoutes);
router.use("/extracurricular-staff", extracurricularStaffRoutes);
router.use("/extracurricular-portal", extracurricularPortalRoutes);
router.use("/registration-requests", registrationRequestRoutes);
router.use("/syllabus", syllabusRoutes);
// Platform tier — super_admin only (see superAdmin.routes.ts).
router.use("/super-admin", superAdminRoutes);
router.use("/school-requests", schoolRequestRoutes);
router.use("/website-knowledge", websiteKnowledgeRoutes);
router.use("/learning-games", learningGamesRoutes);
// classRoutes mounts both /classes and /subjects itself (see class.routes.ts)
router.use("/", classRoutes);
// rbacRoutes mounts /roles and /permissions itself (see rbac.routes.ts)
router.use("/", rbacRoutes);

export default router;
