import { Router } from "express";
import * as controller from "../controllers/tracking.controller";
import { requireAuth, requirePermission, requireRole } from "../middleware/auth.middleware";
import { validate } from "../middleware/validate.middleware";
import { listTripHistorySchema, locationSchema, markStudentStatusSchema, recordMyLocationSchema, startTripSchema, studentIdParamSchema, tripParamSchema } from "../validators/tracking.validator";
const router = Router(); router.use(requireAuth);
router.post("/driver/trips", requireRole("driver"), validate(startTripSchema), controller.startTrip);
router.post("/driver/trips/:tripId/location", requireRole("driver"), validate(locationSchema), controller.recordLocation);
router.post("/driver/trips/:tripId/end", requireRole("driver"), validate(tripParamSchema), controller.endTrip);
router.post("/driver/trips/:tripId/students/:studentId/status", requireRole("driver"), validate(markStudentStatusSchema), controller.markStudentStatus);
router.get("/student/vehicles", requireRole("student"), controller.myVehicles);
router.get("/admin/active-vehicles", requirePermission("transport.view"), controller.activeVehicles);
router.get("/trips", requirePermission("transport.manage"), validate(listTripHistorySchema), controller.listTripHistory);
router.get("/trips/:tripId/eta", validate(tripParamSchema), controller.getTripEta);
router.get("/trips/:tripId/student-status", requirePermission("transport.view"), validate(tripParamSchema), controller.listTripStudentStatus);
router.get("/students/:id/status", validate(studentIdParamSchema), controller.getStudentTripStatus);
router.get("/students/:id/history", validate(studentIdParamSchema), controller.listStudentTransportHistory);
router.post("/students/:id/location", validate(recordMyLocationSchema), controller.recordMyLocation);
export default router;
