import {
  Bus,
  CalendarCheck,
  CalendarDays,
  CalendarOff,
  CalendarRange,
  CarFront,
  CheckCircle2,
  CircleDollarSign,
  ClipboardList,
  GraduationCap,
  Hourglass,
  Layers,
  Megaphone,
  Receipt,
  UserCheck,
  Users,
  UserX,
  Wallet,
  type LucideIcon,
} from "lucide-react";

export const STAT_ICONS: Record<string, LucideIcon> = {
  students: GraduationCap,
  teachers: Users,
  drivers: CarFront,
  classes: Layers,
  sections: Layers,
  attendance: CalendarCheck,
  absent: UserX,
  leave: CalendarOff,
  fee: Wallet,
  pending: Receipt,
  vehicle: Bus,
  exam: ClipboardList,
  announcement: Megaphone,
  feeCollected: CircleDollarSign,
  feeToday: CalendarCheck,
  studentsPaid: UserCheck,
  studentsPending: UserX,
  activityPending: Hourglass,
  activityCompleted: CheckCircle2,
  feeWeek: CalendarDays,
  feeMonth: CalendarDays,
  feeYear: CalendarRange,
};
